name: Release

on:
  workflow_dispatch:
    inputs:
      releaseAs:
        description: 'Release as (major, minor, patch)'
        required: true
        default: 'minor'

jobs:

  test-cross-compile-and-release:
    name: Create Changelog and Tag
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Create Changelog and Tag
      run: npx standard-version --release-as ${{ github.event.inputs.releaseAs }}

    - name: Push
      run: git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" --follow-tags
